### ISSUE TITLE
Initializing a number to a range crashes the program

### ISSUE THREAD

**Issue by kkevlar** [flipturnapps/TSTL-Java#4]
In tstl the user should be able to type

``` tstl
pool: Integer %INT%
...
%INT% := %[1..30]%
```

to generate actions for each possible initialization of %INT%, 1-30.  However this breaks the program.  More work needs to be done.

**Comment by agroce** [comment]
How does it break?  Is it supposed to be handled now?  Test case?  :)

On Wed, Jun 24, 2015 at 2:33 PM, Kevin Kellar notifications@github.com
wrote:

> Assigned #4 https://github.com/flipturnapps/TSTL-Java/issues/4 to
> @agroce https://github.com/agroce.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/flipturnapps/TSTL-Java/issues/4#event-339420537.

## 

## 

Alex David Groce
School of Electrical Engineering and Computer Science
Oregon State University

**Comment by kkevlar** [comment]
No it will be my next sub-project.  Right now TSTL thinks all values in "%" symbols is a variable, and as such, throws a MalformedTstlException because "[1..30]" is not a pool variable.  Sorry for assigning you I pressed the wrong button.

**Comment by kkevlar** [comment]
As of the fix numrange bug [commit](../commit/3d2dcdd7debbe7a3f6f391b938458a0b60d9c0df), using ranges as definitions for integers is legal, doesn't crash, and an action is created for each of them.
